version: "1"
services:
  db:
    image: mysql:8.0
    env_file:
      - .env
    platform: ${PLATFORM}
    volumes:
      - ./db:/var/lib/mysql
    container_name: mysql8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_local
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: password
  WordPress:
    image: wordpress:latest
    env_file:
      - .env
    container_name: wordpress
    restart: always
    depends_on:
      - db
    ports:
      - ${WP_PORT}:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: db_local
      WORDPRESS_DEBUG:
    volumes:
      - ./app:/var/www/html
